services:
  dev-container-movis:
    # platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-container-movis
    ports:
      - "127.0.0.1:3000:3000" # HTTP access: https://localhost:3000/
      - "127.0.0.1:3001:3001" # HTTPS access: https://localhost:3001/
      - "127.0.0.1:3002:6901" # HTTPS access (direct KasmVNC, no audio): https://localhost:3002/
    security_opt:
      - seccomp=unconfined
    volumes:
      - dev_container_data_movis:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - TITLE=Dev-movis
volumes:
  dev_container_data_movis: